
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mybi_dbt_ramm'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mybi_dbt_ramm'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
    account_id_ads: "30595"
    account_id_amocrm: "30350"
    account_id_currency: "33199"
    account_id_direct: "30596, 33206, 33207"
    account_id_facebook: "30246, 30610, 32296, 33162, 33203, 35748"

sources:
    # ONLY ENABLE NECESSARY SOURCES FROM CORE MODULE
    mybi_dbt_core:
        sources:
            +enabled: false
            ads:
                +enabled: true
            amocrm:
                +enabled: true
            currency:
                +enabled: true
            direct:
                +enabled: true
            facebook:
                +enabled: true
            general:
                +enabled: true

models:
    # ONLY ENABLE NECESSARY MODELS FROM CORE MODULE
    mybi_dbt_core:   
        staging:
            +enabled: false
            ads:
                +enabled: true
            amocrm:
                +enabled: true
            currency:
                +enabled: true
            direct:
                +enabled: true
            facebook:
                +enabled: true
            general:
                +enabled: true

    mybi_dbt_ramm:
        +materialized: table
        
        staging:
            tags: ["staging"]
        
        intermediate:
            tags: ["intermediate"]

        # marts:
        #     tags: ["marts"]
