
name: 'mybi_dbt_planoplan'
version: '1.0.0'
config-version: 2

profile: 'mybi_dbt_planoplan'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  pg_planoplan: 'pg_planoplan'
  pg_planoplan_host: 'db.planoplan.com:5432'
  pg_planoplan_database: 'planoplan'

models:
    mybi_dbt_planoplan:
        +materialized: table
        +tags: ["planoplan"]

        postgres:
            +enabled: false
            +tags: ["postgres"]
            +schema: "postgres"

        flatten:
            +enabled: false
            +tags: ["flatten"]
            +schema: "flatten"
            +tags: ["flatten"]
            order_by: ["ga_dimension13"]

        staging:
            +tags: ["staging"]
            +schema: "staging"
            +tags: ["staging"]
            # engine: "ReplacingMergeTree()"
            order_by: ["key_dt_session_id"]
            partition_by: ["toYYYYMM(dt)"]
            # +post-hook: "OPTIMIZE TABLE {{ this }} FINAL DEDUPLICATE"
        
        intermediate:
            +tags: ["intermediate"]
            +schema: "intermediate"
            order_by: ["key_dt_session_id"]
            partition_by: ["toYYYYMM(dt)"]            
      
        marts:
            tags: ["marts"]

            dim:
                tags: ["dim"]
            
            fct:
                # normalized fact tables
                +enabled: True
                tags: ["fct"]
                order_by: ["key_dt_session_id"]
                partition_by: ["toYYYYMM(dt)"]            

            facts:
                # denormalized fact tables
                +enabled: False
                tags: ["facts"]
                order_by: ["session_id"]
                partition_by: ["toYYYYMM(dt)"]
