version: 2

sources:

  - name: ga
    # database: planoplan
    schema: planoplan
    tags: ["sources", "ga"]      
    # freshness:
    #   warn_after: {count: 12, period: hour}
    #   error_after: {count: 24, period: hour}
    # loaded_at_field: created_at
    description: ""

    tables:
      - name: seances
        identifier: analytics_report_31267
        description: "GA_Сеансы"
      - name: pageviews
        identifier: analytics_report_31268
        description: "GA_Просмотры страниц"
      - name: events
        identifier: analytics_report_31269
        description: "GA_События"
      - name: traffic_sources_utm
        identifier: analytics_report_31270
        description: "GA_Источники трафика (все utm)"
      - name: devices
        identifier: analytics_report_31271
        description: "GA_Устройства"
      - name: places
        identifier: analytics_report_31272
        description: "GA_Местоположение"
      - name: languages
        identifier: analytics_report_31273
        description: "GA_Язык"
      - name: goals
        identifier: analytics_report_31280
        description: "GA_Цели"
      - name: transactions
        identifier: analytics_report_31281
        description: "GA_Транзакции"
      - name: users
        identifier: analytics_report_31282
        description: "GA_Параметры посетителей"
      - name: traffic_sources_full_path
        identifier: analytics_report_31283
        description: "GA_Источники трафика (полный путь)"
      - name: registration_polls
        identifier: analytics_report_33098
        description: "GA_Опрос при регистрации"