version: 2

sources:

  - name: hist
    # database: planoplan
    schema: mybi
    tags: ["sources", "ga"]      
    # freshness:
    #   warn_after: {count: 12, period: hour}
    #   error_after: {count: 24, period: hour}
    # loaded_at_field: created_at
    description: "myBI database with historical data"

    tables:

      - name: seances
        identifier: analytics_report_31267
        description: "GA_Сеансы"
      - name: pageviews
        identifier: analytics_report_31268
        description: "GA_Просмотры страниц"
      - name: events
        identifier: analytics_report_31269
        description: "GA_События"
      - name: traffic_sources_utm
        identifier: analytics_report_31270
        description: "GA_Источники трафика (все utm)"
      - name: devices
        identifier: analytics_report_31271
        description: "GA_Устройства"
      - name: places
        identifier: analytics_report_31272
        description: "GA_Местоположение"
      - name: languages
        identifier: analytics_report_31273
        description: "GA_Язык"
      - name: goals
        identifier: analytics_report_31280
        description: "GA_Цели"
      - name: transactions
        identifier: analytics_report_31281
        description: "GA_Транзакции"
      - name: users
        identifier: analytics_report_49168
        description: "GA_Параметры посетителей"
      - name: traffic_sources_full_path
        identifier: analytics_report_31283
        description: "GA_Источники трафика (полный путь)"
      - name: registration_polls
        identifier: analytics_report_33098
        description: "GA_Опрос при регистрации"
      - name: platforms
        identifier: analytics_report_49901
        description: "GA_Платформа"        

  - name: mybi_fhqjlqs
    schema: mybi_fhqjlqs
    description: '1. Платформа'
    tables:
      - name: platforms
        identifier: analytics_report_64990
        description: ''

  - name: mybi_rnayzsc
    schema: mybi_rnayzsc
    description: '2. События-Цели'
    tables:
      - name: events
        identifier: analytics_report_64991
        description: ''
      - name: goals
        identifier: analytics_report_64992
        description: ''

  - name: mybi_dtftgmb
    schema: mybi_dtftgmb
    description: '3. Сеансы-Посетители-Источники '
    tables:
      - name: traffic_sources_utm
        identifier: analytics_report_64993
        description: ''
      - name: traffic_sources_full_path
        identifier: analytics_report_64994
        description: ''
      - name: seances
        identifier: analytics_report_64995
        description: ''
      - name: users
        identifier: analytics_report_64996
        description: ''

  - name: mybi_qfjrlkq
    schema: mybi_qfjrlkq
    description: '4. Транз-Опрос-Место-Яз-Устр-ва'
    tables:
      - name: transactions
        identifier: analytics_report_64997
        description: ''
      - name: registration_polls
        identifier: analytics_report_64998
        description: ''
      - name: devices
        identifier: analytics_report_65001
        description: ''
      - name: places
        identifier: analytics_report_65002
        description: ''
      - name: languages
        identifier: analytics_report_65003
        description: ''


  - name: render
    schema: postgres
    tags: ["sources", "postgres"]      
    description: "PostgreSQL CRM database 'render'"
    config:
      enabled: false

    tables:

      - name: tasks
        identifier: _airbyte_raw_tasks

  - name: planoplan
    schema: postgres
    tags: ["sources", "postgres"]      
    description: "PostgreSQL CRM database 'planoplan'"
    config:
      enabled: false    

    tables:

      - name: render_tasks
        identifier: render_tasks
      - name: events
        identifier: _airbyte_raw_events
      - name: payments
        identifier: _airbyte_raw_payments
      - name: users
        identifier: _airbyte_raw_users
      - name: store_goods
        identifier: _airbyte_raw_store_goods
      - name: store_sets
        identifier: _airbyte_raw_store_sets
      - name: tariffs
        identifier: _airbyte_raw_tariffs
      - name: tariffs_stat
        identifier: _airbyte_raw_tariffs_stat
      - name: clients
        identifier: _airbyte_raw_clients
      - name: teams
        identifier: _airbyte_raw_teams
      - name: promocodes
        identifier: _airbyte_raw_promocodes

  - name: planoplan_mv
    schema: planoplan_postgres
    tags: ["sources", "postgres"]      
    description: "Materialized Views on top of Postgres tables"
    config:
      enabled: false    

    tables:

      - name: tasks
        identifier: render_tasks
        columns:
          - name: id
            tests:
                - not_null
                - unique          
      - name: render_tasks
        identifier: planoplan_render_tasks
        columns:
          - name: id
            tests:
                - not_null
                - unique          
      - name: events
        identifier: planoplan_events
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: payments
        identifier: planoplan_payments
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: users
        identifier: planoplan_users
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: store_goods
        identifier: planoplan_store_goods
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: store_sets
        identifier: planoplan_store_sets
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: tariffs
        identifier: planoplan_tariffs
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: tariff_stat
        identifier: planoplan_tariff_stat
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: clients
        identifier: planoplan_clients
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: teams
        identifier: planoplan_teams
        columns:
          - name: id
            tests:
                - not_null
                - unique            
      - name: promocodes
        identifier: planoplan_promocodes
        columns:
          - name: id
            tests:
                - not_null
                - unique            










