
version: 2

models:
  - name: stg_costs
    description: ""
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null

  - name: stg_amocrm_united
    description: ""
    columns:
      - name: id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null