
version: 2

models:

  - name: stg_devices
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_events
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_goals
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_languages
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_pageviews
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_places
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_registration_polls
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_seances
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_traffic_sources_full_path
    description: ""
    tests:
      - unique:
          column_name: (session_id || ga_channelgrouping || ga_source || ga_medium)
          severity: warn
    columns:
      - name: session_id
        description: ""
        tests:
          # - unique:`
              # severity: warn
          - not_null

  - name: stg_traffic_sources_utm
    description: ""
    tests:
      - unique:
          column_name: (session_id || ga_channelgrouping || ga_source || ga_medium)    
          severity: warn
    columns:
      - name: session_id
        description: ""
        tests:
          # - unique:
              # severity: warn
          - not_null

  - name: stg_transactions
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_users
    description: ""
    columns:
      - name: session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

