
version: 2

models:

  - name: stg_devices
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_events
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_goals
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_languages
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_pageviews
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_places
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_registration_polls
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_seances
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_traffic_sources_full_path
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_traffic_sources_utm
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_transactions
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

  - name: stg_users
    description: ""
    columns:
      - name: key_dt_session_id
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null

